name: Test and Tag
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      bump:
        description: 'The type of semantic version increment to make'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
          - none
      dry_run:
        description: 'If true, only calculate the new version and exit successfully.'
        required: false
        default: false

permissions:
  contents: write
  packages: read

env:
  AZURE_AD_APP_ID: 451f36c7-ae84-4cdc-a13d-68c75f88fc8c
  AZURE_WEBAPP_NAME: connect-admin-enosix
  RESOURCE_GROUP: mgmt-dashboard
  bump: ${{ github.event_name == 'pull_request' && 'none' || github.event_name == 'workflow_dispatch' && github.event.inputs.bump || 'patch' }}
  prerelease_version: ${{ github.event_name == 'pull_request' && format('pr{0}', github.event.number) || '' }}
  dry_run: ${{ github.event_name == 'pull_request' && 'true' || github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run || 'false' }}

jobs:
  test-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Get Secrets
        uses: bitwarden/sm-action@1238aae8fc64b212641190a9227c8a734ab1a793 # v3.0.1
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          secrets: |
            d494f42b-8a60-431a-aef9-b18501149f57 > AZURE_CLIENT_ID
            80ba47f3-5ce7-493a-8c79-b1850114b58b > AZURE_CLIENT_SECRET
            8e976875-589b-4731-a1c5-b1850114e158 > AZURE_SUBSCRIPTION_ID
            370453a3-d0da-46f4-a456-b1850114f67e > AZURE_TENANT_ID

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Test Action
        uses: ./
        with:
          azure_client_id: ${{ env.AZURE_CLIENT_ID }}
          azure_client_secret: ${{ env.AZURE_CLIENT_SECRET }}
          azure_subscription_id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ env.AZURE_TENANT_ID }}
          azure_webapp_name: ${{ env.AZURE_WEBAPP_NAME }}
          resource_group: ${{ env.RESOURCE_GROUP }}
          deployment_slot: ghac-azure-web-app
          ad_app_id: ${{ env.AZURE_AD_APP_ID }}
          image: ghcr.io/enosix/connect-admin-ui:main

      - name: Remove slot
        run: |
          az webapp deployment slot delete --name ${AZURE_WEBAPP_NAME} --resource-group ${RESOURCE_GROUP} --slot ghac-azure-web-app

      - name: Generate Semantic Version
        uses: enosix/github-action-generate-semver@4ab2e5251fb8c5b9b06eb65b22c0e25daba76311 # v4.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          bump: ${{ env.bump }}
          prerelease_version: ${{ env.prerelease_version }}
          dry_run: ${{ env.dry_run }}
          detect_bump: true
